//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ezipay.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class AddDuringPayRecord
    {
        public int AddDuringPayRecordId { get; set; }
        public string amount { get; set; }
        public string channel { get; set; }
        public string customer { get; set; }
        public string ISD { get; set; }
        public string invoiceNo { get; set; }
        public string Comment { get; set; }
        public string serviceCategory { get; set; }
        public Nullable<int> ServiceCategoryId { get; set; }
        public Nullable<int> chennelId { get; set; }
        public string Password { get; set; }
        public string OrderNo { get; set; }
        public string TransactionNo { get; set; }
        public Nullable<bool> IsAddDuringPay { get; set; }
        public Nullable<long> WalletUserId { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public Nullable<int> TransactionStatus { get; set; }
        public Nullable<bool> IsMerchant { get; set; }
        public Nullable<long> MerchantId { get; set; }
    }
}
