//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ezipay.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class balance161022
    {
        public long walletuserid { get; set; }
        public string firstname { get; set; }
        public string lastname { get; set; }
        public string emailid { get; set; }
        public string stdcode { get; set; }
        public Nullable<double> mobileno { get; set; }
        public Nullable<double> currentbalance { get; set; }
        public Nullable<System.DateTime> createddate { get; set; }
    }
}
