//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ezipay.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class CallbackListTracking
    {
        public long Id { get; set; }
        public int CallBackId { get; set; }
        public int Status { get; set; }
        public long CeatedBy { get; set; }
        public System.DateTime CreatedOn { get; set; }
    
        public virtual Callback Callback { get; set; }
    }
}
