//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ezipay.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class CardPaymentResponse
    {
        public long CardPaymentResponseId { get; set; }
        public string vpc_AVSResultCode { get; set; }
        public string vpc_AcqAVSRespCode { get; set; }
        public string vpc_AcqCSCRespCode { get; set; }
        public string vpc_AcqResponseCode { get; set; }
        public string vpc_AuthorizeId { get; set; }
        public string vpc_BatchNo { get; set; }
        public string vpc_CSCResultCode { get; set; }
        public string vpc_Card { get; set; }
        public string vpc_Command { get; set; }
        public string vpc_Currency { get; set; }
        public string vpc_Locale { get; set; }
        public string vpc_Merchant { get; set; }
        public string vpc_Message { get; set; }
        public string vpc_ReceiptNo { get; set; }
        public string vpc_SecureHash { get; set; }
        public string vpc_TransactionNo { get; set; }
        public string vpc_TxnResponseCode { get; set; }
        public string vpc_Version { get; set; }
        public string vpc_VerType { get; set; }
        public string vpc_VerStatus { get; set; }
        public string vpc_VerToken { get; set; }
        public string vpc_VerSecurityLevel { get; set; }
        public string vpc_3DSenrolled { get; set; }
        public string vpc_3DSXID { get; set; }
        public string vpc_3DSECI { get; set; }
        public string vpc_3DSstatus { get; set; }
        public string vpc_hashValidated { get; set; }
        public string vpc_ResponseCodeDescription { get; set; }
        public string vpc_StatusCodeDescription { get; set; }
        public Nullable<long> CardPaymentRequestId { get; set; }
    
        public virtual CardPaymentRequest CardPaymentRequest { get; set; }
    }
}
