//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ezipay.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Carduseinaddmoney
    {
        public long Id { get; set; }
        public Nullable<long> WalletUserId { get; set; }
        public string CardNo { get; set; }
        public string RequestedBankTxnId { get; set; }
        public string ResponseBankTxnId { get; set; }
        public string RequestedamountXOF { get; set; }
        public string TotalamountXOF { get; set; }
        public string InvoiceNumber { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public string EmailId { get; set; }
    
        public virtual WalletUser WalletUser { get; set; }
    }
}
