//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ezipay.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class CardNoDuplicate
    {
        public long Id { get; set; }
        public Nullable<long> WalletUserId { get; set; }
        public string CardNo { get; set; }
        public string EmailId { get; set; }
        public string Mobile_No { get; set; }
        public string CurrentBalance { get; set; }
        public Nullable<System.DateTime> UserCreatedDate { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string CreatedBy { get; set; }
    }
}
