//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ezipay.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cashdeposituser_addmoney
    {
        public int id { get; set; }
        public long WalletUserId { get; set; }
        public string DepositorName { get; set; }
        public string DepositorCashAmount { get; set; }
        public string DepositorCountry { get; set; }
        public string DepositorCountryCode { get; set; }
        public string DepositorSlipImage { get; set; }
        public Nullable<System.DateTime> UploadedDate { get; set; }
        public string DepositStatus { get; set; }
        public string Reason { get; set; }
        public Nullable<System.DateTime> DepositStatusUpdateDate { get; set; }
        public string Isactive { get; set; }
        public string TotalDepositorAmount { get; set; }
        public string TransactiontID { get; set; }
    }
}
