//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ezipay.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChargeBack
    {
        public long id { get; set; }
        public Nullable<long> Walletuserid { get; set; }
        public string UserEmail { get; set; }
        public string UserMobileNo { get; set; }
        public Nullable<bool> IsActiveStatus { get; set; }
        public string CurrentBalance { get; set; }
        public string AmountLimit { get; set; }
        public string Createdby { get; set; }
        public Nullable<System.DateTime> Createddate { get; set; }
        public string DeleteFlag { get; set; }
        public string Deleteby { get; set; }
        public Nullable<System.DateTime> Deleteddate { get; set; }
        public string Comment { get; set; }
    }
}
