//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ezipay.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class CommisionMaster
    {
        public long CommisionMasterId { get; set; }
        public Nullable<int> WalletServiceId { get; set; }
        public Nullable<decimal> CommisionPercent { get; set; }
        public Nullable<long> CreatedBy { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public Nullable<decimal> FlatCharges { get; set; }
        public Nullable<decimal> BenchmarkCharges { get; set; }
        public Nullable<decimal> VATCharges { get; set; }
    
        public virtual WalletService WalletService { get; set; }
        public virtual WalletService WalletService1 { get; set; }
        public virtual WalletService WalletService2 { get; set; }
        public virtual WalletService WalletService3 { get; set; }
        public virtual WalletService WalletService4 { get; set; }
        public virtual WalletService WalletService5 { get; set; }
        public virtual WalletService WalletService6 { get; set; }
        public virtual WalletService WalletService7 { get; set; }
    }
}
