//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ezipay.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class ErrorLog
    {
        public long ErrorId { get; set; }
        public string ErrorMessage { get; set; }
        public string ClassName { get; set; }
        public string MethodName { get; set; }
        public string JsonData { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
    }
}
