//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ezipay.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class HotelMaster
    {
        public int Id { get; set; }
        public string HotelName { get; set; }
        public string HotelImage { get; set; }
        public string Location { get; set; }
        public string PdfUrl { get; set; }
        public Nullable<long> AvailableRooms { get; set; }
        public Nullable<long> NoOfRooms { get; set; }
        public Nullable<decimal> CostOfRooms { get; set; }
        public Nullable<long> MaxGuest { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.DateTime> UpDatedDate { get; set; }
    }
}
