//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ezipay.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class MasterCardPaymentRequest
    {
        public int Id { get; set; }
        public string SessionId { get; set; }
        public string Version { get; set; }
        public string SuccessIndicator { get; set; }
        public string Merchant { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public Nullable<long> WalletUserId { get; set; }
        public string Amount { get; set; }
        public string CommissionAmount { get; set; }
        public string TotalAmount { get; set; }
        public string TransactionNo { get; set; }
        public Nullable<decimal> FlatCharges { get; set; }
        public Nullable<decimal> BenchmarkCharges { get; set; }
        public Nullable<decimal> CommisionCharges { get; set; }
    }
}
