//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ezipay.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class MobileMoneySenderDetail
    {
        public long Id { get; set; }
        public Nullable<long> WalletuserId { get; set; }
        public string SenderIdNumber { get; set; }
        public string SenderIdType { get; set; }
        public Nullable<System.DateTime> SenderDateofbirth { get; set; }
        public string SenderAddress { get; set; }
        public string SenderCity { get; set; }
        public Nullable<System.DateTime> Createddate { get; set; }
        public string ReceiverFirstName { get; set; }
        public string ReceiverLastName { get; set; }
    }
}
