//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ezipay.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Navigation
    {
        public long NavigationId { get; set; }
        public string NgRoutes { get; set; }
        public string NgIcon { get; set; }
        public string Navigation1 { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public Nullable<long> ParentId { get; set; }
        public Nullable<int> NavigationOrder { get; set; }
        public string NavigationUrl { get; set; }
        public string Icon { get; set; }
        public string ControllerName { get; set; }
        public string ActionName { get; set; }
        public string Functions { get; set; }
    }
}
