//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ezipay.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class OneTimePassword
    {
        public long OtpId { get; set; }
        public string MobileNo { get; set; }
        public string Otp { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> OtpCounter { get; set; }
        public Nullable<int> Callbackcounter { get; set; }
    }
}
