//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ezipay.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class PayMoneyRequest
    {
        public long PayMoneyRequestId { get; set; }
        public string Amount { get; set; }
        public string Comments { get; set; }
        public Nullable<long> SenderId { get; set; }
        public Nullable<long> ReceiverId { get; set; }
        public Nullable<bool> IsPaid { get; set; }
        public Nullable<System.DateTime> DateofPay { get; set; }
        public Nullable<long> WalletTransactionId { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public Nullable<int> TransactionTypeInfo { get; set; }
    }
}
