//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ezipay.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class SessionToken
    {
        public long SessionTokenId { get; set; }
        public Nullable<long> WalletUserId { get; set; }
        public string TokenValue { get; set; }
        public string DeviceUniqueId { get; set; }
        public string PublicKey { get; set; }
        public string PrivateKey { get; set; }
        public Nullable<System.DateTime> IssuedTime { get; set; }
        public Nullable<System.DateTime> ExpiryTime { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public string IPaddress { get; set; }
    
        public virtual WalletUser WalletUser { get; set; }
        public virtual WalletUser WalletUser1 { get; set; }
        public virtual WalletUser WalletUser2 { get; set; }
        public virtual WalletUser WalletUser3 { get; set; }
    }
}
