//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ezipay.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class ShareAndEarnDetail
    {
        public int Id { get; set; }
        public Nullable<long> ReceiverId { get; set; }
        public Nullable<long> SenderId { get; set; }
        public string ReferUrl { get; set; }
        public string SenderReferalPoint { get; set; }
        public string SenderReferalAmount { get; set; }
        public string ReceiverReferalPoints { get; set; }
        public string ReceiverReferalAmount { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
    }
}
