//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ezipay.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class ShareAndEarnMaster
    {
        public int Id { get; set; }
        public Nullable<int> ReceiverPoints { get; set; }
        public Nullable<decimal> ConversionPoint { get; set; }
        public Nullable<int> SenderPoints { get; set; }
        public Nullable<decimal> ConversionPointsValue { get; set; }
        public Nullable<decimal> MinimumRedeemablePoint { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
    }
}
