//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ezipay.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class TransferToBankResponse1
    {
        public long TransferToBankResponseId { get; set; }
        public string AmountXOF { get; set; }
        public string ResponseDescription { get; set; }
        public Nullable<System.DateTime> TransactionDate { get; set; }
        public string TransactionStatus { get; set; }
        public string Responsecode { get; set; }
        public Nullable<System.DateTime> Requestdatetime { get; set; }
        public string AccountToDebit { get; set; }
        public string AccountToCredit { get; set; }
        public string Reference { get; set; }
        public string Narration { get; set; }
        public string Remarks { get; set; }
        public string NameToCredit { get; set; }
        public string bankname { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public Nullable<long> TransferToBankRequestId { get; set; }
    }
}
