//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ezipay.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class TransferToBankRequest
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TransferToBankRequest()
        {
            this.TransferToBankResponses = new HashSet<TransferToBankResponse>();
            this.TransferToBankResponses1 = new HashSet<TransferToBankResponse>();
        }
    
        public long TransferToBankRequestId { get; set; }
        public string OrderNo { get; set; }
        public string TransactionNo { get; set; }
        public Nullable<long> WalletUserId { get; set; }
        public string Amount { get; set; }
        public string DestAcctName { get; set; }
        public string DestAcctNumber { get; set; }
        public string ServiceTransId { get; set; }
        public string DestBankCode { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public string MobileNo { get; set; }
        public string ISDCode { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TransferToBankResponse> TransferToBankResponses { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TransferToBankResponse> TransferToBankResponses1 { get; set; }
        public virtual WalletUser WalletUser { get; set; }
        public virtual WalletUser WalletUser1 { get; set; }
    }
}
