//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ezipay.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class TransferToBankResponse
    {
        public long TransferToBankResponseId { get; set; }
        public string Amount { get; set; }
        public Nullable<System.DateTime> DateTime { get; set; }
        public string TrackingNum { get; set; }
        public string FunctionCode { get; set; }
        public string OrigineBank { get; set; }
        public string DestBank { get; set; }
        public string SessionId { get; set; }
        public string ChannelCode { get; set; }
        public string NameToDebit { get; set; }
        public string AccountToDebit { get; set; }
        public string NameToCredit { get; set; }
        public string AccountToCredit { get; set; }
        public string Narration { get; set; }
        public string ActCode { get; set; }
        public string AprvCode { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public Nullable<long> TransferToBankRequestId { get; set; }
    
        public virtual TransferToBankRequest TransferToBankRequest { get; set; }
        public virtual TransferToBankRequest TransferToBankRequest1 { get; set; }
    }
}
