//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ezipay.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserBlockUnblockDetail
    {
        public long id { get; set; }
        public Nullable<long> Walletuserid { get; set; }
        public Nullable<bool> BlockUnblock { get; set; }
        public string BlockByEmailid { get; set; }
        public Nullable<System.DateTime> Blockdate { get; set; }
        public string UnBlockByEmailid { get; set; }
        public Nullable<System.DateTime> UnBlockdate { get; set; }
        public string Comment { get; set; }
    }
}
