//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ezipay.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class ViewUserList
    {
        public Nullable<long> RowNumber { get; set; }
        public long WalletUserId { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string EmailId { get; set; }
        public string StdCode { get; set; }
        public string MobileNo { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> UserType { get; set; }
        public string Country { get; set; }
        public string ProfileImage { get; set; }
        public string Currentbalance { get; set; }
        public string DeviceToken { get; set; }
        public Nullable<int> DeviceType { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public Nullable<int> DocumetStatus { get; set; }
        public Nullable<bool> IsEmailVerified { get; set; }
        public Nullable<bool> IsOtpVerified { get; set; }
    }
}
