//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ezipay.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_walletsummary
    {
        public long WalletUserId { get; set; }
        public string FullName { get; set; }
        public string EmailId { get; set; }
        public string StdCode { get; set; }
        public string MobileNo { get; set; }
        public string WalletState { get; set; }
        public string Country { get; set; }
        public Nullable<decimal> CurrentBal { get; set; }
    }
}
