//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ezipay.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class WalletTransaction_Back
    {
        public long WalletTransactionId { get; set; }
        public string TotalAmount { get; set; }
        public Nullable<int> CommisionId { get; set; }
        public string CommisionAmount { get; set; }
        public string WalletAmount { get; set; }
        public Nullable<decimal> ServiceTaxRate { get; set; }
        public string ServiceTax { get; set; }
        public Nullable<int> WalletServiceId { get; set; }
        public Nullable<long> SenderId { get; set; }
        public Nullable<long> ReceiverId { get; set; }
        public string AccountNo { get; set; }
        public string TransactionId { get; set; }
        public Nullable<bool> IsAdminTransaction { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public string Comments { get; set; }
        public string InvoiceNo { get; set; }
        public Nullable<int> TransactionStatus { get; set; }
        public string TransactionType { get; set; }
        public Nullable<int> TransactionTypeInfo { get; set; }
        public Nullable<bool> IsBankTransaction { get; set; }
        public string BankBranchCode { get; set; }
    }
}
