//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ezipay.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class WalletService
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public WalletService()
        {
            this.CommisionMasters = new HashSet<CommisionMaster>();
            this.CommisionMasters1 = new HashSet<CommisionMaster>();
            this.CommisionMasters2 = new HashSet<CommisionMaster>();
            this.CommisionMasters3 = new HashSet<CommisionMaster>();
            this.CommisionMasters4 = new HashSet<CommisionMaster>();
            this.CommisionMasters5 = new HashSet<CommisionMaster>();
            this.CommisionMasters6 = new HashSet<CommisionMaster>();
            this.CommisionMasters7 = new HashSet<CommisionMaster>();
        }
    
        public int WalletServiceId { get; set; }
        public string ServiceName { get; set; }
        public Nullable<int> ServiceCategoryId { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public Nullable<long> MerchantId { get; set; }
        public string ImageUrl { get; set; }
        public string BankCode { get; set; }
        public string HttpVerbs { get; set; }
        public string IsdCode { get; set; }
        public string description { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CommisionMaster> CommisionMasters { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CommisionMaster> CommisionMasters1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CommisionMaster> CommisionMasters2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CommisionMaster> CommisionMasters3 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CommisionMaster> CommisionMasters4 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CommisionMaster> CommisionMasters5 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CommisionMaster> CommisionMasters6 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CommisionMaster> CommisionMasters7 { get; set; }
    }
}
