//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ezipay.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class WalletTransactionDetail
    {
        public long WalletTransactionDetailId { get; set; }
        public string Amount { get; set; }
        public Nullable<int> TransactionType { get; set; }
        public Nullable<long> WalletUserId { get; set; }
        public Nullable<long> WalletTransactionId { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
    
        public virtual WalletUser WalletUser { get; set; }
        public virtual WalletUser WalletUser1 { get; set; }
        public virtual WalletUser WalletUser2 { get; set; }
        public virtual WalletUser WalletUser3 { get; set; }
    }
}
