//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ezipay.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class WalletUser
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public WalletUser()
        {
            this.BankDetails = new HashSet<BankDetail>();
            this.Cardnewaddrequests = new HashSet<Cardnewaddrequest>();
            this.CardPaymentRequests = new HashSet<CardPaymentRequest>();
            this.CardPaymentRequest_Back = new HashSet<CardPaymentRequest_Back>();
            this.CardPaymentRequest_Back1 = new HashSet<CardPaymentRequest_Back>();
            this.Carduseinaddmoneys = new HashSet<Carduseinaddmoney>();
            this.MerchantDocuments = new HashSet<MerchantDocument>();
            this.MerchantStores = new HashSet<MerchantStore>();
            this.Notifications = new HashSet<Notification>();
            this.Notifications1 = new HashSet<Notification>();
            this.Notifications2 = new HashSet<Notification>();
            this.Notifications3 = new HashSet<Notification>();
            this.Notifications4 = new HashSet<Notification>();
            this.Notifications5 = new HashSet<Notification>();
            this.Notifications6 = new HashSet<Notification>();
            this.Notifications7 = new HashSet<Notification>();
            this.SessionTokens = new HashSet<SessionToken>();
            this.SessionTokens1 = new HashSet<SessionToken>();
            this.SessionTokens2 = new HashSet<SessionToken>();
            this.SessionTokens3 = new HashSet<SessionToken>();
            this.TransferToBankRequests = new HashSet<TransferToBankRequest>();
            this.TransferToBankRequests1 = new HashSet<TransferToBankRequest>();
            this.TransferToBankRequest1 = new HashSet<TransferToBankRequest1>();
            this.WalletTransactionDetails = new HashSet<WalletTransactionDetail>();
            this.WalletTransactionDetails1 = new HashSet<WalletTransactionDetail>();
            this.WalletTransactionDetails2 = new HashSet<WalletTransactionDetail>();
            this.WalletTransactionDetails3 = new HashSet<WalletTransactionDetail>();
        }
    
        public long WalletUserId { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string StdCode { get; set; }
        public string MobileNo { get; set; }
        public string EmailId { get; set; }
        public string Otp { get; set; }
        public string QrCode { get; set; }
        public Nullable<bool> IsOtpVerified { get; set; }
        public Nullable<int> CurrencyId { get; set; }
        public string CurrentBalance { get; set; }
        public Nullable<int> UserType { get; set; }
        public Nullable<long> AdminUserId { get; set; }
        public string PublicKey { get; set; }
        public string PrivateKey { get; set; }
        public Nullable<bool> IsEmailVerified { get; set; }
        public string HashedPassword { get; set; }
        public byte[] HashedSalt { get; set; }
        public string DeviceToken { get; set; }
        public Nullable<int> DeviceType { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public byte[] OtpHashedSalt { get; set; }
        public Nullable<bool> IsFirstTimeUser { get; set; }
        public Nullable<bool> IsTemporaryPassword { get; set; }
        public string ProfileImage { get; set; }
        public Nullable<bool> IsNotification { get; set; }
        public string EmailAuthToken { get; set; }
        public string UserAddress { get; set; }
        public Nullable<int> DocumetStatus { get; set; }
        public string Countries { get; set; }
        public Nullable<bool> IsDisabledTransaction { get; set; }
        public Nullable<int> MerchantType { get; set; }
        public string BusinessLicense { get; set; }
        public Nullable<double> Latitude { get; set; }
        public Nullable<double> Longitude { get; set; }
        public string TinNumber { get; set; }
        public string VatNumber { get; set; }
        public string PostalCode { get; set; }
        public Nullable<int> AppVersion { get; set; }
        public Nullable<decimal> EarnedPoints { get; set; }
        public Nullable<decimal> EarnedAmount { get; set; }
        public Nullable<bool> IsNewQrCode { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BankDetail> BankDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Cardnewaddrequest> Cardnewaddrequests { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CardPaymentRequest> CardPaymentRequests { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CardPaymentRequest_Back> CardPaymentRequest_Back { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CardPaymentRequest_Back> CardPaymentRequest_Back1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Carduseinaddmoney> Carduseinaddmoneys { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MerchantDocument> MerchantDocuments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MerchantStore> MerchantStores { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Notification> Notifications { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Notification> Notifications1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Notification> Notifications2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Notification> Notifications3 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Notification> Notifications4 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Notification> Notifications5 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Notification> Notifications6 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Notification> Notifications7 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SessionToken> SessionTokens { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SessionToken> SessionTokens1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SessionToken> SessionTokens2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SessionToken> SessionTokens3 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TransferToBankRequest> TransferToBankRequests { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TransferToBankRequest> TransferToBankRequests1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TransferToBankRequest1> TransferToBankRequest1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WalletTransactionDetail> WalletTransactionDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WalletTransactionDetail> WalletTransactionDetails1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WalletTransactionDetail> WalletTransactionDetails2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WalletTransactionDetail> WalletTransactionDetails3 { get; set; }
    }
}
